name: Node CI

on:
  schedule:
  - cron: "0 0 * * *"
  push:
    branches:
      - 'master'
    paths:
      - '.github/**.yml'
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Install xmllint
      run: sudo apt-get install -y libxml2-utils
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/checkout@v3
    - name: generate
      run: |
        yarn && ./index.js && ./merge.sh
      env:
        CI: true
    - name: pandoc opml 2 html
      uses: maxheld83/pandoc@v2
      with:
        args: "./generate/all.opml --standalone  -o ./generate/all.html --from opml --to html5" # gets appended to pandoc command
        #args: "--standalone --output=output/index.html input.txt"
    - name: git commit
      run: |
        git config user.name "githubaction"
        git config user.email "lotosbin+githubaction@gmail.com"
        git checkout master
        git add data/*
        git add generate/*
        git commit -m "feat: update opml files"
        git push
